urls.py
from django.urls import path
from django.contrib.auth import views
from django.views.generic import RedirectView
from profile.forms.main import *
from profile.views.main import *
from django.urls import reverse_lazy

# To change the app name.
app_name = 'profile'
urlpatterns = [
    # Main Views
    path(
        '',
        IndexView.as_view(),
        name='home'
    ),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name='dashboard'
    ),

    # Profile
    path(
        'accounts/',
        RedirectView.as_view(pattern_name='profile:index'),
        name='redirect'
    ),
    path(
        'accounts/profile/',
        ProfileView.as_view(),
        name='index'
    ),

    # Authentication
    path(
        'accounts/login/',
        views.LoginView.as_view(
            form_class=StyledAuthenticationForm,
            template_name='profile/authentication/login.html',
            extra_context={
                'signup_form': StyledUserCreationForm()
            }
        ),
        name='login'
    ),
    path(
        'accounts/register/',
        UserCreationView.as_view(),
        name='register'
    ),
    path(
        'accounts/<int:id>/edit/',
        UserEditView.as_view(),
        name='edit_user'
    ),
    path(
        'accounts/<int:id>/delete/',
        UserDeletionView.as_view(),
        name='delete_user'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(
            template_name='profile/authentication/logged_out.html'
        ),
        name='logout'
    ),

    # Password
    path(
        'accounts/password/change/',
        views.PasswordChangeView.as_view(
            form_class=StyledPasswordChangeForm,
            template_name='profile/authentication/change_password.html',
            success_url=reverse_lazy('profile:change_done')
        ),
        name='change_password'
    ),
    path(
        'accounts/password/change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='profile/authentication/change_done.html'
        ),
        name='change_done'
    ),
    path(
        'accounts/password/reset/',
        views.PasswordResetView.as_view(
            form_class=StyledPasswordResetForm,
            template_name='profile/authentication/reset_password.html',
            success_url=reverse_lazy('profile:reset_done')
        ),
        name='reset_password'
    ),
    path(
        'accounts/password/reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='profile/authentication/reset_done.html'
        ),
        name='reset_done'
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='profile/authentication/reset_confirm.html',
            form_class=StyledPasswordResetForm,
            success_url=reverse_lazy('profile:reset_complete')
        ),
        name='reset_confirm'
    ),
    path(
        'accounts/password/reset/complete/',
        views.PasswordResetCompleteView.as_view(
            template_name='profile/authentication/reset_complete.html',
        ),
        name='reset_complete'
    ),
]

templates/profile/includes/components/messages.html
<ul class="list-unstyled mb-0">
    {% for message in messages %}
        <li>
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show d-flex align-items-center gap-4" role="alert">
                <span class="badge bg-{% if message.tags %}{{ message.tags }}{% endif %} rounded-pill">
                    {{ message.tags|capfirst }}
                </span>
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </li>
    {% endfor %}
</ul>

templates/profile/includes/components/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 rounded-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'profile:home' %}">
            {% translate 'Profile' %}
        </a>
        <button class="navbar-toggler collapsed p-2 rounded-circle" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    {% url 'profile:home' as home %}
                    <a class="nav-link{% if request.path == home %} active{% endif %}"
                       href="{{ home }}">
                        <i class="bi bi-house-fill"></i>
                        {% translate 'Home' %}
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link" data-bs-toggle="dropdown" href="#">
                        <i class="bi bi-person-circle"></i>
                        {% translate 'Profile' %}
                    </a>
                    <div class="dropdown-menu shadow rounded-2">
                        <a class="dropdown-item d-flex gap-4" href="{% url 'profile:index' %}">
                            <i class="bi bi-house"></i>
                            {% translate 'Home' %}
                        </a>
                        <a class="dropdown-item d-flex gap-4" href="{% url 'profile:dashboard' %}">
                            <i class="bi bi-gear"></i>
                            {% translate 'Dashboard' %}
                        </a>
                        <a class="dropdown-item d-flex gap-4" href="{% url 'profile:change_password' %}">
                            <i class="bi bi-key"></i>
                            {% translate 'Change Password' %}
                        </a>
                        <a class="dropdown-item d-flex gap-4" href="{% url 'profile:reset_password' %}">
                            <i class="bi bi-lock"></i>
                            {% translate 'Reset Password' %}
                        </a>
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item d-flex gap-4" href="{% url 'profile:edit_user' request.user.id %}">
                                <i class="bi bi-pencil"></i>
                                {% translate 'Edit Account' %}
                            </a>
                            <a class="dropdown-item d-flex gap-4"
                               href="{% url 'profile:delete_user' request.user.id %}">
                                <i class="bi bi-trash"></i>
                                {% translate 'Delete Account' %}
                            </a>
                        {% else %}
                            <a class="dropdown-item d-flex gap-4" href="{% url 'profile:login' %}">
                                <i class="bi bi-box-arrow-in-right"></i>
                                {% translate 'Login for more' %}
                            </a>
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/youzarsiph/profile.git">
                        <i class="bi bi-github"></i>
                        {% translate 'Github' %}
                    </a>
                </li>
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link" href="{% url 'profile:logout' %}">
                            <i class="bi bi-power"></i>
                            {% translate 'Log out' %}
                        </a>
                    {% else %}
                        <a class="nav-link" href="{% url 'profile:login' %}">
                            <i class="bi bi-box-arrow-in-right"></i>
                            {% translate 'Login' %}
                        </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/profile/includes/components/sidebar.html
{% load i18n %}
<nav class="navbar navbar-dark bg-primary navbar-expand-lg align-items-lg-start h-100 rounded-3">
    <div class="container flex-lg-column align-items-lg-start h-100 w-100">
        <button class="navbar-toggler rounded-circle p-2" data-bs-toggle="collapse" data-bs-target="#sidebar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand d-lg-none me-0" href="#">
            {% translate 'Menu' %}
        </a>
        <ul class="navbar-nav flex-row flex-lg-column order-lg-last mt-lg-auto w-lg-100">
            <li class="nav-item px-3 px-lg-0 py-lg-2">
                <a class="nav-link d-flex gap-4" href="{% url 'profile:index' %}">
                    <i class="bi bi-person-circle"></i>
                    <span class="d-none d-lg-inline">
                        {% translate 'Account' %}
                    </span>
                </a>
            </li>
            <li class="nav-item d-none d-lg-block">
                <a class="nav-link d-flex gap-4" href="{% url 'profile:logout' %}">
                    <i class="bi bi-power"></i>
                    {% translate 'Log out' %}
                </a>
            </li>
        </ul>
        <div class="collapse navbar-collapse mb-auto align-items-lg-start w-100" id="sidebar">
            <ul class="navbar-nav flex-lg-column w-100">
                <li class="nav-item">
                    {% url 'profile:dashboard' as dashboard %}
                    <a class="nav-link d-flex gap-4{% if request.path == dashboard %} active{% endif %}"
                       href="{{ dashboard }}">
                        <i class="bi bi-house"></i>
                        {% translate 'Home' %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex gap-4" href="#">
                        <i class="bi bi-link"></i>
                        {% translate 'Link' %}
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link d-flex gap-4" href="#" id="navbarDropdown2" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-menu-app"></i>
                        {% translate 'Dropdown' %}
                    </a>
                    <ul class="dropdown-menu position-lg-static" aria-labelledby="navbarDropdown2">
                        <li>
                            <a class="dropdown-item" href="#">
                                {% translate 'Action' %}
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                {% translate 'Another action' %}
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                {% translate 'Something else here' %}
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex gap-4 disabled" href="#" tabindex="-1" aria-disabled="true">
                        <i class="bi bi-slash"></i>
                        {% translate 'Disabled' %}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>