urls.py
from django.urls import path
from django.contrib.auth import views
from django.views.generic import RedirectView
from profile.forms.main import *
from profile.views.main import *
from django.urls import reverse_lazy

# To change the app name.
app_name = 'profile'
urlpatterns = [
    # Main Views
    path(
        '',
        IndexView.as_view(),
        name='home'
    ),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name='dashboard'
    ),

    # Profile
    path(
        'accounts/',
        RedirectView.as_view(pattern_name='profile:index'),
        name='redirect'
    ),
    path(
        'accounts/profile/',
        ProfileView.as_view(),
        name='index'
    ),

    # Authentication
    path(
        'accounts/login/',
        views.LoginView.as_view(
            form_class=StyledAuthenticationForm,
            template_name='profile/authentication/login.html',
            extra_context={
                'signup_form': StyledUserCreationForm()
            }
        ),
        name='login'
    ),
    path(
        'accounts/register/',
        UserCreationView.as_view(),
        name='register'
    ),
    path(
        'accounts/<int:id>/edit/',
        UserEditView.as_view(),
        name='edit_user'
    ),
    path(
        'accounts/<int:id>/delete/',
        UserDeletionView.as_view(),
        name='delete_user'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(
            template_name='profile/authentication/logged_out.html'
        ),
        name='logout'
    ),

    # Password
    path(
        'accounts/password/change/',
        views.PasswordChangeView.as_view(
            form_class=StyledPasswordChangeForm,
            template_name='profile/authentication/change_password.html',
            success_url=reverse_lazy('profile:change_done')
        ),
        name='change_password'
    ),
    path(
        'accounts/password/change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='profile/authentication/change_done.html'
        ),
        name='change_done'
    ),
    path(
        'accounts/password/reset/',
        views.PasswordResetView.as_view(
            form_class=StyledPasswordResetForm,
            template_name='profile/authentication/reset_password.html',
            success_url=reverse_lazy('profile:reset_done')
        ),
        name='reset_password'
    ),
    path(
        'accounts/password/reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='profile/authentication/reset_done.html'
        ),
        name='reset_done'
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='profile/authentication/reset_confirm.html',
            form_class=StyledPasswordResetForm,
            success_url=reverse_lazy('profile:reset_complete')
        ),
        name='reset_confirm'
    ),
    path(
        'accounts/password/reset/complete/',
        views.PasswordResetCompleteView.as_view(
            template_name='profile/authentication/reset_complete.html',
        ),
        name='reset_complete'
    ),
]

templates/profile/authentication/change_done.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Chnage Done' %}{% endblock %}
{% block breadcrumb %}
    <div class="card card-body mb-4">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'profile:index' %}">
                    {% translate 'Profile' %}
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'profile:change_password' %}">
                    {% translate 'Password Change' %}
                </a>
            </li>
            <li class="breadcrumb-item active">
                {% translate 'Done' %}
            </li>
        </ol>
    </div>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Password change successful' %}
    </h1>
    <p class="col-md-8 fs-4">
        {% translate 'Your password was changed.' %}
    </p>
    <a class="btn btn-primary btn-lg" role="button" href="{% url 'profile:login' %}">
        {% translate 'Login' %}
    </a>
{% endblock %}

templates/profile/authentication/change_password.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Change Password' %}{% endblock %}
{% block breadcrumb %}
    <div class="card card-body mb-4">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'profile:index' %}">
                    {% translate 'Profile' %}
                </a>
            </li>
            <li class="breadcrumb-item active">
                {% translate 'Password Change' %}
            </li>
        </ol>
    </div>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Password Change' %}
    </h1>
    <p>
        {% blocktranslate %}
            Please enter your old password, for security’s sake, and then enter your new password twice so we can verify
            you typed it in correctly.
        {% endblocktranslate %}
    </p>
    {% include 'profile/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
    {% url 'profile:index' as url %}
    {% include 'profile/includes/utilties/submit.html' with form_id='form' reset=1 cancel_url=url %}
{% endblock %}

templates/profile/authentication/logged_out.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Logged out' %}{% endblock %}
{% block breadcrumb %}{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Logged out' %}
    </h1>
    <p class="lead fs-3">
        {% translate 'Thanks for your time.' %}
    </p>
{% endblock %}

templates/profile/authentication/login.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Login' %}{% endblock %}
{% block breadcrumb %}{% endblock %}
{% block content %}
    <h1 class="display-1 text-center">
        {% translate 'Welcome' %}
    </h1>
    <div class="d-flex align-items-center justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-signin-tab" data-bs-toggle="tab"
                            data-bs-target="#nav-signin"
                            type="button" role="tab" aria-controls="nav-signin" aria-selected="true">
                        {% translate 'Log In' %}
                    </button>
                    <button class="nav-link" id="nav-signup-tab" data-bs-toggle="tab" data-bs-target="#nav-signup"
                            type="button" role="tab" aria-controls="nav-signup" aria-selected="false">
                        {% translate 'Register' %}
                    </button>
                </div>
            </nav>
            <div class="card border-top-0" style="border-top-right-radius: 0; border-top-left-radius: 0">
                <div class="card-body">
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-signin" role="tabpanel"
                             aria-labelledby="nav-signin-tab">
                            <h1 class="fs-1 lead text-primary card-title">
                                {% translate 'Log In' %}
                            </h1>
                            {% include 'profile/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
                            {% url 'profile:index' as url %}
                            {% include 'profile/includes/utilties/submit.html' with form_id='form' reset=1 cancel_url=url %}
                        </div>
                        <div class="tab-pane fade" id="nav-signup" role="tabpanel" aria-labelledby="nav-signup-tab">
                            <h1 class="fs-1 lead text-primary card-title">
                                {% translate 'Register' %}
                            </h1>
                            {% url 'profile:register' as action %}
                            {% include 'profile/includes/utilties/form.html' with form_tag=1 form=signup_form method='post' action=action id='signup_form' floating_labels=1 %}
                            {% include 'profile/includes/utilties/submit.html' with form_id='signup_form' reset=1 cancel_url=url %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profile/authentication/profile.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Profile' %}{% endblock %}
{% block content %}
    <div class="row g-4">
        <div class="col-12 col-md-6">
            <h1 class="display-1">
                {% translate 'Welcome ' %}{{ request.user.username }}
            </h1>
            <p class="lead fs-4">
                {% blocktranslate %}
                    Welcome to your profile, here you will find links to edit, delete your account, change and reset
                    your password.
                {% endblocktranslate %}
            </p>
            <div class="d-lg-flex d-grid align-items-center gap-4 mt-4">
                <a class="btn btn-warning btn-lg d-inline-flex gap-4 text-white"
                   href="{% url 'profile:edit_user' request.user.id %}">
                    <i class="bi bi-pencil"></i>
                    {% translate 'Edit Account' %}
                </a>
                <a class="btn btn-danger btn-lg d-inline-flex gap-4"
                   href="{% url 'profile:delete_user' request.user.id %}">
                    <i class="bi bi-trash"></i>
                    {% translate 'Delete Account' %}
                </a>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="d-grid gap-4">
                <div class="card rounded-3 bg-dark text-white">
                    <div class="card-body">
                        <h2 class="display-6">
                            {% translate 'Change the password' %}
                        </h2>
                        <p>
                            {% blocktranslate %}
                                Here you can change your password.
                            {% endblocktranslate %}
                        </p>
                        <a href="{% url 'profile:change_password' %}"
                           class="btn btn-outline-light btn-lg d-inline-flex gap-4">
                            <i class="bi bi-key"></i>
                            {% translate 'Change' %}
                        </a>
                    </div>
                </div>
                <div class="card rounded-3">
                    <div class="card-body">
                        <h2 class="display-6">
                            {% translate 'Reset Password' %}
                        </h2>
                        <p>
                            {% blocktranslate %}
                                Or if you want to reset your password.
                            {% endblocktranslate %}
                        </p>
                        <a class="btn btn-outline-secondary btn-lg d-inline-flex gap-4" role="button"
                           href="{% url 'profile:reset_password' %}">
                            <i class="bi bi-lock"></i>
                            {% translate 'Reset' %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profile/authentication/reset_complete.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Complete' %}{% endblock %}
{% block breadcrumb %}
    <div class="card card-body mb-4">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'profile:index' %}">
                    {% translate 'Profile' %}
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'profile:reset_password' %}">
                    {% translate 'Password Reset' %}
                </a>
            </li>
            <li class="breadcrumb-item">
                {% translate 'Complete' %}
            </li>
        </ol>
    </div>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Password reset complete' %}
    </h1>
    <p class="col-md-8 fs-4">
        {% translate 'Your password has been set. You may go ahead and log in now.' %}
    </p>
    <a class="btn btn-primary btn-lg" role="button" href="{% url 'profile:login' %}">
        {% translate 'Login' %}
    </a>
{% endblock %}

templates/profile/authentication/reset_confirm.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Confirmation' %}{% endblock %}
{% block breadcrumb %}
    <div class="card card-body mb-4">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'profile:index' %}">
                    {% translate 'Profile' %}
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'profile:reset_password' %}">
                    {% translate 'Password Reset' %}
                </a>
            </li>
            <li class="breadcrumb-item">
                {% translate 'Confirm' %}
            </li>
        </ol>
    </div>
{% endblock %}
{% block content %}
    {% if validlink %}
        <h1>
            {% translate 'Password Reset Confirm' %}
        </h1>
        <p>
            {% translate "Please enter your new password twice so we can verify you typed it in correctly." %}
        </p>
        {% include 'profile/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
        {% url 'profile:index' as url %}
        {% include 'profile/includes/utilties/submit.html' with form_id='form' reset=1 cancel_url=url %}
    {% else %}
        <h1>
            {% translate 'The password reset link was invalid!' %}
        </h1>
        <p>
            {% blocktranslate %}
                The password reset link was invalid, possibly because it has already been used. Please request a new
                password reset.
            {% endblocktranslate %}
        </p>
        <a class="btn btn-lg btn-primary" href="{% url 'profile:reset_password' %}">
            {% translate 'Request Password Reset' %}
        </a>
    {% endif %}
{% endblock %}

templates/profile/authentication/reset_done.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Done' %}{% endblock %}
{% block breadcrumb %}
    <div class="card card-body mb-4">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'profile:index' %}">
                    {% translate 'Prfile' %}
                </a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'profile:reset_password' %}">
                    {% translate 'Password Reset' %}
                </a>
            </li>
            <li class="breadcrumb-item active">
                {% translate 'Done' %}
            </li>
        </ol>
    </div>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Password reset sent' %}
    </h1>
    <p class="col-md-8 fs-4">
        {% blocktranslate %}
            We’ve emailed you instructions for setting your password, if an account exists with the email you
            entered. You should receive them shortly.
            If you don’t receive an email, please make sure you’ve entered the address you registered with, and
            check your spam folder.
        {% endblocktranslate %}
    </p>
    <a href="{% url 'profile:login' %}" class="btn btn-primary btn-lg" role="button">
        {% translate 'Login' %}
    </a>
{% endblock %}

templates/profile/authentication/reset_password.html
{% extends 'profile/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Reset Password' %}{% endblock %}
{% block breadcrumb %}
    <div class="card card-body mb-4">
        <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item">
                <a href="{% url 'profile:index' %}">
                    {% translate 'Profile' %}
                </a>
            </li>
            <li class="breadcrumb-item active">
                {% translate 'Password Reset' %}
            </li>
        </ol>
    </div>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Reset Password' %}
    </h1>
    <p>
        {% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}
    </p>
    {% include 'profile/includes/utilties/form.html' with form_tag=1 method='post' floating_labels=1 %}
    {% url 'profile:index' as url %}
    {% include 'profile/includes/utilties/submit.html' with form_id='form' reset=1 cancel_url=url %}
{% endblock %}